import Header from "@/components/header";
import "./globals.css";
import { Lato, Roboto } from "next/font/google";

const inter = Roboto({
  weight: ["400", "700", "500"],
  preload: false,
  style: ["normal"],
  subsets: ["latin"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Header /> */}
        <main className="flex min-h-[calc(100vh-48px)] flex-col items-center justify-center p-10"> {children}</main>
      </body>
    </html>
  );
}
