import Header from "@/components/header";
import "./globals.css";
import { Lato, Roboto } from "next/font/google";
import { MdMenu } from "react-icons/md";

const inter = Roboto({
  weight: ["400", "700", "500"],
  preload: false,
  style: ["normal"],
  subsets: ["latin"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen items-center justify-center overflow-hidden bg-[url('/assets/images/img1.jpg')] bg-cover bg-no-repeat bg-bottom">
          <Header />
          <div className="min-h-screen flex items-center flex-[11] max-h-full p-10 bg-black/[.80]">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
